server:
  port: 8910
spring:
  datasource:
    url: jdbc:mysql://47.107.163.168:3306/pig?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    host: 47.107.163.168
    port: 6379
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5